Mention that we are an open source project based in a university #1184
PowerPointLabs/PowerPointLabs-Website pull request #56
Opened 2017-03-18 11:01 UTC by jamos-tay

Fixes PowerPointLabs/PowerPointLabs#1184

Updated Description.

2017-03-18 12:40 UTC, damithc commented on index.html
> +			PowerPointLabs is an open source project based in the National University of Singapore. It makes creating engaging PowerPoint presentations easy. <strong>Check out what it can do for you below.</s
Bold `open source project` and `National University of Singapore`? Can link each too (first one to github and second one to SoC website)

2017-03-19 11:45 UTC, jamos-tay commented on index.html
> +			PowerPointLabs is an open source project based in the National University of Singapore. It makes creating engaging PowerPoint presentations easy. <strong>Check out what it can do for you below.</s
Sure.

Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/19278089/24080546/a1b8e296-0cdc-11e7-932f-c99196d3ab1c.png)

2017-03-20 01:36 UTC, Skaty requested changes
Minor nitpick.

2017-03-20 01:36 UTC, Skaty commented on index.html
> +			PowerPointLabs is an <a href="https://github.com/PowerPointLabs/PowerPointLabs"><strong>open source project</strong></a> based in the <a href="http://www.comp.nus.edu.sg/">National University of S
It would be better if we can link to HTTPS versions of the websites if possible.

2017-03-20 04:17 UTC, jamos-tay commented on index.html
> +			PowerPointLabs is an <a href="https://github.com/PowerPointLabs/PowerPointLabs"><strong>open source project</strong></a> based in the <a href="http://www.comp.nus.edu.sg/">National University of S
Thanks, done

2017-03-20 04:32 UTC, Skaty approved these changes
LGTM.

2017-03-29 16:01 UTC, merged